<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
 <xacro:include filename="inertial_macros.xacro" />
    <xacro:property name="chassis_length" value="0.55"/>
    <xacro:property name="chassis_width" value="0.4"/>
    <xacro:property name="chassis_height" value="0.25"/>
    <xacro:property name="chassis_mass" value="0.5"/>
    <xacro:property name="wheel_radius" value="0.065"/>
    <xacro:property name="wheel_thickness" value="0.06"/>
    <xacro:property name="wheel_mass" value="0.1"/>
    <xacro:property name="wheel_offset_x" value="0.45"/>
    <xacro:property name="wheel_offset_y" value="0.2"/>

<material name="white">
    <color rgba="1 1 1 1"/>
</material>

<material name="orange">
    <color rgba="1 0.3 0.1 1"/>
</material>

<material name="blue">
    <color rgba="0.2 0.2 1 1"/>
</material>

<material name="red">
    <color rgba="1 0 0 1"/>
</material>

<material name="black">
    <color rgba="0 0 0 1"/>
</material>

<!-- BASE LINK -->
<link name="base_link">

</link>

<!-- BASE_FOOTPRINT LINK -->
<joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="base_footprint">
</link>

<!-- CHASSIS LINK -->
<joint name="chasis_joint" type="fixed">
  <parent link="base_link"/>
  <child link="chassis"/>
  <origin xyz="-0.1 0 0"/>
</joint>

<link name="chassis">
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="blue"/>
    </visual>

    <collision>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
     <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>
<gazebo reference="chassis">
    <material>Gazebo/Blue</material>
</gazebo>

<!-- Back LEFT WHEEL -->
<joint name="back_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="back_left_wheel">
    <visual>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>
<gazebo reference="back_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>
<!-- BACK RIGHT WHEEL -->

<joint name="back_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
</joint>

<link name="back_right_wheel">
    <visual>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>
<gazebo reference="back_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>


<!-- FRONT LEFT WHEEL -->
<joint name="front_left_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="front_left_wheel">
    <visual>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    
</link>
<gazebo reference="front_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>
<!-- FRONT RIGHT WHEEL -->

<joint name="front_right_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
</joint>

<link name="front_right_wheel">
    <visual>
        <geometry>
         <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

 <gazebo reference="front_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>   

</robot>